# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: (^tests/results/)
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: (^deploy/helm-chart/templates)
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-vcs-permalinks
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
      - id: detect-private-key
        exclude: (^examples/|^docs/|.*_test.go$)

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types:
          - javascript

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint-full

  # Rules are in .markdownlint-cli2.yaml file
  # See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for rule descriptions
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.11.0
    hooks:
      - id: markdownlint-cli2-fix

  # Rules are in .yamllint.yaml file
  # See https://yamllint.readthedocs.io/en/stable/rules.html# for rule descriptions
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint

ci:
  skip: [golangci-lint-full, prettier, markdownlint-cli2-fix, yamllint]
  autofix_prs: false
